<Project>
  <PropertyGroup>
    <Hd2RuntimeGuiVersion>0.2.0</Hd2RuntimeGuiVersion>
    <VersionPrefix Condition="'$(VersionPrefix)' == ''">$(Hd2RuntimeGuiVersion)</VersionPrefix>
    <Version Condition="'$(Version)' == ''">$(Hd2RuntimeGuiVersion)</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(Hd2RuntimeGuiVersion).0</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(Hd2RuntimeGuiVersion).0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Hd2RuntimeGuiVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
