<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Metadata/Bundled/metadata.json" />
    <EmbeddedResource Include="Metadata/Bundled/PlayerWeaponAuthoringCapabilities.json" />
    <EmbeddedResource Include="Metadata/Bundled/PlayerWeaponAmmoCapabilities.json" />
  </ItemGroup>
</Project>
