using HD2RuntimeGUI.Core.Localization;
using HD2RuntimeGUI.Core.Metadata;
using HD2RuntimeGUI.Core.Services;
using Xunit;

namespace HD2RuntimeGUI.Tests;

// Projects saved by ModBuilder 1.3.1 itself (Fixtures/projects-1.3.1, generated by the v1.3.1 source against SDK 0.27.0: weapons, a
// projectile swap, a support weapon, stratagems, a vehicle and backpack, the SG-20 Halt case, a booster and a throwable). 1.4.0 must open
// each one unchanged on its own SDK, in either UI language, and generate exactly 1.3.1's operations, now each inside the pcall wrapper
// (*.v140.lua is *.v131.lua with only that wrapper applied; for the SG-20 Halt also the branch-qualified field constants that fix
// ModBuilder#2 on HD2Runtime 0.27.0). Rebinding to the pinned SDK is an explicit user action and keeps the edits.
public sealed class OldProjectCompatibilityTests
{
    private static string Folder => Path.Combine(AppContext.BaseDirectory, "Fixtures", "projects-1.3.1");
    public static IEnumerable<object[]> Projects() => Directory.GetFiles(Folder, "*.hd2mod.json").Select(f => new object[] { Path.GetFileName(f)[..^".hd2mod.json".Length] });

    private static async Task<BuilderWorkspace> Open(TestEnvironment e, string name)
    {
        // The user's data folder after upgrading: SDK 0.27.0 installed and current, then 1.4.0 starts with its newer bundled SDK.
        await SdkFixtures.Install(e, "0.27.0");
        var upgraded = new SdkCache(e.Paths, e.Reader, e.GitHub); e.GitHub.Offline = true;
        var w = new BuilderWorkspace(e.Store, e.Projects, upgraded, new SdkUpdateService(upgraded, e.GitHub, e.Paths), e.Changes, e.Generator, e.Exporter, e.Desktop, e.Desktop, e.Paths);
        await w.InitializeAsync();
        Assert.Equal(SdkPin.Version, w.SdkStatus!.Installed.Version);
        var project = await e.Store.ImportAsync(Path.Combine(Folder, name + ".hd2mod.json"));
        await w.OpenAsync(project.Id);
        return w;
    }

    [Theory] [MemberData(nameof(Projects))]
    public async Task A_1_3_1_project_opens_unchanged_and_generates_its_operations_in_either_language(string name)
    {
        var expected = File.ReadAllText(Path.Combine(Folder, name + ".v140.lua")).Replace("\r\n", "\n");
        foreach (var language in UiLanguages.Supported)
            using (UiCulture.Use(language))
            {
                using var e = new TestEnvironment(); var w = await Open(e, name);
                Assert.Equal("0.27.0", w.Project!.SdkVersion); Assert.Null(w.BuildError);
                Assert.Equal(expected, w.LuaPreview);
                if (name == "P6-sg20-halt")
                {
                    // 1.3.1 wrote the generic constants that published 0.27.0 could not resolve on the Halt feeds; everything else is identical.
                    var v131 = File.ReadAllText(Path.Combine(Folder, name + ".v131.lua"));
                    Assert.Contains("hd2.fields.projectile.velocity,", v131); Assert.Contains("hd2.fields.projectile.alternate_velocity,", w.LuaPreview);
                    Assert.Contains("hd2.fields.damage.player_standard_damage,", v131); Assert.Contains("hd2.fields.damage.primary_standard_damage,", w.LuaPreview);
                }
                // Opening never rewrites the saved project (its format and edits stay as 1.3.1 wrote them).
                Assert.True(w.Project.FormatVersion <= 9);
            }
    }

    [Theory] [MemberData(nameof(Projects))]
    public async Task Rebinding_a_1_3_1_project_to_the_pinned_sdk_keeps_its_edits(string name)
    {
        using var e = new TestEnvironment(); var w = await Open(e, name);
        var before = w.Project!.WeaponChanges.Count + w.Project.SupportChanges.Count + w.Project.StratagemChanges.Count + w.Project.EntityChanges.Count + w.Project.ProjectileChanges.Count;
        await w.RebindToInstalledSdkAsync();
        Assert.Equal(SdkPin.Version, w.Project!.SdkVersion);
        Assert.Equal(before, w.Project.WeaponChanges.Count + w.Project.SupportChanges.Count + w.Project.StratagemChanges.Count + w.Project.EntityChanges.Count + w.Project.ProjectileChanges.Count);
        // A rebind either builds directly or names what needs review; it never silently drops an edit.
        Assert.True(w.BuildError == null || w.BuildError.Length > 0);
        if (name == "P6-sg20-halt") { Assert.Null(w.BuildError); Assert.Contains("hd2.weapon('SG-20 Halt')", w.LuaPreview); }
    }
}
